### ISSUE TITLE
Learn more links to wrong tree detail

### ISSUE THREAD

**Issue by vitoc** [cheeaun/exploretrees-sg#1]
Clicking on the Learn more button for the below for example:

![image](https://user-images.githubusercontent.com/558813/56413335-c419ae80-62b9-11e9-8631-00bd128acdb8.png)

I get pointed to:

https://florafaunaweb.nparks.gov.sg/Special-Pages/plant-detail.aspx?id=1800

Which is not the right plant/tree:

![image](https://user-images.githubusercontent.com/558813/56413362-da276f00-62b9-11e9-8e0f-e75080901351.png)

**Comment by cheeaun** [comment]
Oh wow, nice find! I checked and turns out... they have a new URL now 😅

OLD: https://florafaunaweb.nparks.gov.sg/Special-Pages/plant-detail.aspx?id=1800
NEW: https://florafaunaweb.nparks.gov.sg/Special-Pages/plant-detail-master.aspx?id=1800

I'll update to the new URL in a new version soon 👍

**Comment by vitoc** [comment]
👍

**Comment by cheeaun** [comment]
Fixed in latest V2 release. Closing this issue.
