### ISSUE TITLE
Download trees data

### ISSUE THREAD

**Issue by rampallishyam** [cheeaun/exploretrees-sg#2]
Hi Cheeaun,

Thanks for the beautiful website. I am trying to get the data of all the trees in Singapore. I have some difficulties understanding your code since I only have the knowledge of Python. Can you help me to know how to download the trees with all their points and data of height for ex. ?

I am using this data for development purpose just like you.

**Comment by cheeaun** [comment]
There are few scripts to run as documented on the README's `Technicalities` section https://github.com/cheeaun/exploretrees-sg#technicalities

In short, you'll need node.js and then run these commands in the folder:

```
> npm run trees
> npm run chunk
```

**OR** you can download the data from the [Releases page](https://github.com/cheeaun/exploretrees-sg/releases) available in GeoJSON format.

**Comment by rampallishyam** [comment]
Thanks a lot for the suggestion. Now I have the data.
